"""initial schema: users, workspaces, plans, social

Revision ID: 50b86c0f4875
Revises: 
Create Date: 2026-07-23 11:51:39.791861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b86c0f4875'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('monthly_price_usd', sa.Float(), nullable=True),
    sa.Column('annual_price_usd', sa.Float(), nullable=True),
    sa.Column('connected_accounts', sa.Integer(), nullable=True),
    sa.Column('posts_per_month', sa.Integer(), nullable=True),
    sa.Column('ai_text_per_month', sa.Integer(), nullable=True),
    sa.Column('ai_images_per_month', sa.Integer(), nullable=True),
    sa.Column('ai_videos_per_month', sa.Integer(), nullable=True),
    sa.Column('templates', sa.Integer(), nullable=True),
    sa.Column('brand_voice', sa.Boolean(), nullable=True),
    sa.Column('approval_workflow', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_overrides_plan_key'), 'plan_overrides', ['plan_key'], unique=True)
    op.create_table('social_ai_usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_ai_usage_events_created_at'), 'social_ai_usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_ai_usage_events_kind'), 'social_ai_usage_events', ['kind'], unique=False)
    op.create_index(op.f('ix_social_ai_usage_events_user_id'), 'social_ai_usage_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_social_ai_usage_events_workspace_id'), 'social_ai_usage_events', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('plan', sa.Enum('starter', 'growth', 'enterprise', name='workspace_plan'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_user_id'), 'workspaces', ['owner_user_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'x', name='social_platform'), nullable=False),
    sa.Column('account_type', sa.Enum('page', 'profile', 'group', name='social_account_type'), nullable=False),
    sa.Column('platform_account_id', sa.String(length=128), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_picture_url', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'platform_account_id', name='uq_social_accounts_org_platform_account')
    )
    op.create_index('ix_social_accounts_org_id', 'social_accounts', ['workspace_id'], unique=False)
    op.create_index('ix_social_accounts_org_platform', 'social_accounts', ['workspace_id', 'platform'], unique=False)
    op.create_table('social_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_audit_logs_created_at', 'social_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_social_audit_logs_org_id', 'social_audit_logs', ['workspace_id'], unique=False)
    op.create_table('social_brand_voices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('brand_name', sa.String(length=160), nullable=False),
    sa.Column('industry', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('tones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('words_to_use', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('words_to_avoid', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cta_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentence_length', sa.Enum('short', 'medium', 'long', name='social_sentence_length'), nullable=False),
    sa.Column('emoji_usage', sa.Enum('never', 'sometimes', 'often', name='social_emoji_usage'), nullable=False),
    sa.Column('primary_language', sa.String(length=16), nullable=False),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', name='uq_social_brand_voices_org_id')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'scheduled', 'publishing', 'published', 'failed', 'archived', name='social_post_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_status', sa.Enum('not_required', 'pending', 'approved', 'rejected', 'changes_requested', name='social_approval_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_source', sa.Enum('uploaded', 'ai_generated', 'none', name='social_image_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_posts_org_id', 'social_posts', ['workspace_id'], unique=False)
    op.create_index('ix_social_posts_org_status', 'social_posts', ['workspace_id', 'status'], unique=False)
    op.create_table('social_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approver_user_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_sla_hours', sa.Integer(), nullable=False),
    sa.Column('approval_sla_action', sa.String(length=32), nullable=False),
    sa.Column('default_posting_times', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('queue_gap_minutes', sa.Integer(), nullable=False),
    sa.Column('blackout_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_tone', sa.String(length=64), nullable=False),
    sa.Column('default_cta', sa.String(length=120), nullable=False),
    sa.Column('hashtag_count', sa.Integer(), nullable=False),
    sa.Column('auto_first_comment', sa.Boolean(), nullable=False),
    sa.Column('image_generation_style', sa.String(length=64), nullable=False),
    sa.Column('openai_model', sa.String(length=64), nullable=False),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('enabled_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_delivery', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', name='uq_social_settings_org_id')
    )
    op.create_table('social_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('caption_template', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('system_key', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=False),
    sa.Column('placeholders', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('generate_image', sa.Boolean(), nullable=False),
    sa.Column('suggested_tone', sa.String(length=64), nullable=False),
    sa.Column('suggested_cta', sa.String(length=160), nullable=False),
    sa.Column('first_comment_template', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_templates_org_id', 'social_templates', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'member', name='workspace_role'), nullable=False),
    sa.Column('social_level', sa.Enum('viewer', 'editor', 'publisher', 'admin', name='social_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_workspace_member_user')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('social_analytics_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'x', name='social_platform'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('new_followers', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('total_reach', sa.Integer(), nullable=False),
    sa.Column('total_impressions', sa.Integer(), nullable=False),
    sa.Column('total_engagements', sa.Integer(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'social_account_id', 'date', name='uq_social_analytics_daily_org_account_date')
    )
    op.create_index('ix_social_analytics_daily_account_date', 'social_analytics_daily', ['social_account_id', 'date'], unique=False)
    op.create_index('ix_social_analytics_daily_org_date', 'social_analytics_daily', ['workspace_id', 'date'], unique=False)
    op.create_table('social_media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='social_media_asset_type'), nullable=False),
    sa.Column('source', sa.Enum('uploaded', 'ai_generated', 'none', name='social_image_source'), nullable=False),
    sa.Column('blob_key', sa.String(length=512), nullable=False),
    sa.Column('blob_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('sora_video_id', sa.String(length=128), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_media_assets_org_created', 'social_media_assets', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_social_media_assets_org_id', 'social_media_assets', ['workspace_id'], unique=False)
    op.create_index('ix_social_media_assets_org_type', 'social_media_assets', ['workspace_id', 'media_type'], unique=False)
    op.create_table('social_post_platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'linkedin', 'x', name='social_platform'), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_comment', sa.Text(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'publishing', 'published', 'failed', 'skipped', name='social_platform_post_status'), nullable=False),
    sa.Column('platform_post_id', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_post_platforms_post_id', 'social_post_platforms', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_social_post_platforms_post_id', table_name='social_post_platforms')
    op.drop_table('social_post_platforms')
    op.drop_index('ix_social_media_assets_org_type', table_name='social_media_assets')
    op.drop_index('ix_social_media_assets_org_id', table_name='social_media_assets')
    op.drop_index('ix_social_media_assets_org_created', table_name='social_media_assets')
    op.drop_table('social_media_assets')
    op.drop_index('ix_social_analytics_daily_org_date', table_name='social_analytics_daily')
    op.drop_index('ix_social_analytics_daily_account_date', table_name='social_analytics_daily')
    op.drop_table('social_analytics_daily')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('ix_social_templates_org_id', table_name='social_templates')
    op.drop_table('social_templates')
    op.drop_table('social_settings')
    op.drop_index('ix_social_posts_org_status', table_name='social_posts')
    op.drop_index('ix_social_posts_org_id', table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_table('social_brand_voices')
    op.drop_index('ix_social_audit_logs_org_id', table_name='social_audit_logs')
    op.drop_index('ix_social_audit_logs_created_at', table_name='social_audit_logs')
    op.drop_table('social_audit_logs')
    op.drop_index('ix_social_accounts_org_platform', table_name='social_accounts')
    op.drop_index('ix_social_accounts_org_id', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_workspaces_owner_user_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_social_ai_usage_events_workspace_id'), table_name='social_ai_usage_events')
    op.drop_index(op.f('ix_social_ai_usage_events_user_id'), table_name='social_ai_usage_events')
    op.drop_index(op.f('ix_social_ai_usage_events_kind'), table_name='social_ai_usage_events')
    op.drop_index(op.f('ix_social_ai_usage_events_created_at'), table_name='social_ai_usage_events')
    op.drop_table('social_ai_usage_events')
    op.drop_index(op.f('ix_plan_overrides_plan_key'), table_name='plan_overrides')
    op.drop_table('plan_overrides')
    # ### end Alembic commands ###
